### ISSUE TITLE
Using wildcards in Dynamic Prompts extension

### ISSUE THREAD

**Issue by adieyal** [devilkkw/StableDiffusion#1]
Really like your collection. Would you mind if I included it in my Auto1111 extension, with attribution? I'm currently linking to the repo but it would make it much easier for users to be able to load wildcards without manual downloads or git. 

[https://github.com/adieyal/sd-dynamic-prompts/tree/main/collections/devilkkw](https://github.com/adieyal/sd-dynamic-prompts/tree/main/collections/devilkkw)

**Comment by devilkkw** [comment]
Thank you. Feel free to add to your great extension.

**Comment by adieyal** [comment]
:)

Thank you
